### ISSUE TITLE
tolong jangan riweh

### ISSUE THREAD

**Issue by ynrrani** [NTsaqif/TikumItikal#1]
apandi diem deh

**Comment by yourrrrelease** [comment]
aaaaaaaaaaa

**Comment by yourrrrelease** [comment]
kick apandi

**Comment by ynrrani** [comment]
setujuuu

**Comment by yourrrrelease** [comment]
bikin apandi nangess

**Comment by ynrrani** [comment]
saya tidak suka mahasiswa yang tidak berkontribusi

**Comment by APANDYYY** [comment]
bersatu kita teguh 
bercerai kita brantakan loh

**Comment by yourrrrelease** [comment]
pak paisall lope you

**Comment by intandelve** [comment]
yara dicari pak totok

**Comment by ynrrani** [comment]
maju bersama nopalll

**Comment by yourrrrelease** [comment]
aku ada tebak tebakan rek

**Comment by APANDYYY** [comment]
berantakan bersama saya

**Comment by yaniarrani** [comment]
pak totok lopyu

**Comment by yourrrrelease** [comment]
hewan-hewan apa yang gaptek?

**Comment by yaniarrani** [comment]
kamu

**Comment by yourrrrelease** [comment]
> berantakan bersama saya

apasihh

**Comment by yaniarrani** [comment]
hehe

**Comment by APANDYYY** [comment]
> hewan-hewan apa yang gaptek?

apa

**Comment by ynrrani** [comment]
> hewan-hewan apa yang gaptek?

kamu, hehe<3

**Comment by APANDYYY** [comment]
jauh di mata dekat dihati apa hayo?

**Comment by yourrrrelease** [comment]
> jauh di mata dekat dihati apa hayo?

puser

**Comment by yourrrrelease** [comment]
> > hewan-hewan apa yang gaptek?
> 
> kamu, hehe<3

kit ati loh akuuu

**Comment by ynrrani** [comment]
> yara dicari pak totok

lopyu pak toto<3

**Comment by yourrrrelease** [comment]
hai

**Comment by APANDYYY** [comment]
****

> > yara dicari pak totok
> 
> lopyu pak toto<3

**iya2 km sipaling totok**
